name: Ubuntu ssh Virtual Machine
on: 
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.5.2
    - name: Run Ubuntu SSH Server
      run: bash linux-ssh.sh
